dist: xenial
language: python
python: 3.6
script: skip

env:
  NGROK_TOKEN: 1RER6BUC3QNNwYWY5LcIBjrv3A8_24QccmopTEQJGMErG9uzw


jobs:
  include:
    - stage: test
    #run eureka tests
    - language: python
      python: 3.6
      before_script:
        - VERSION=`cat version.txt`
        - echo "build eureka version $VERSION"
        - docker build . --build-arg EUREKA_VERSION=${VERSION} -t dinutac/netflixoss-eureka:$VERSION
        - docker pull dinutac/estuary-discovery:latest
      script:
        - python3 -m unittest discover tests "*_test.py"

    - stage: deploy
      services: docker
      deploy:
        - provider: script
          script: bash docker_push_tag.sh
          skip_cleanup: true
          on:
            tags: true

        - provider: script
          script: bash docker_push_master.sh
          skip_cleanup: true
          on:
            branch: master